language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk7
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "fOj3yOWeEQUkRFRFPdWhEG7r6LaKtvncKFy+GrkXEkqZGqC+INF6pqPeZJbut1STaWA4pY3i8JPBdPSuLyVJk9NH5Rr30ZujA3cKg5CQ1fBkzdMrJsRnXMZDMgoooRTyk3OQghB6k0IrCZXBFgewj5VxmPtL2YFgL5k2s9FSSaR2fvJPO+TJiMBDz73f/D5/13wtYiVPHTfFuHPPCIIyaNPpgWhj7Ww2P5pnaoHAuRPh6EsnMZf+66GWIujqeqCpACES9tCePv2AN3egJ4N4UWTXbgKiAkwy4f9p1nNPfGjxIWavskQ5jUEVIDE/7yG/rKmG59AJgpgnMi4rHZxM9dfjAp1nN0HxtnNYzQPupUJmwYhRqJwrB7GZ0pJukHMswadYYCcOx5CGBEJluQlHLdO0/+7YGF55U8/FE9ob+bLo+P2mX2AB9Oqkg8sh2WOwtuGBNVKl714UM8LdTW6odDpgMUK0XlHBed/E8E1uM2JvRBP+BlHNYx2kkLSihXH3EDNKXi1Ol7ntYcBtK2Fcc7pT/DaDzaVA9KLeb8SYdWi9aYgrKTpVOxShuiJLEbCGfYAWISa/5Bb0DLntSsUQg2p9ZsEwWHkqkotWjgp31KAwKMVsBDEFyCMGmtiatn7JILXWEUmiZctuGBQKi1Kdx1aiLM5RWFYyb8mijPYr6D8="
    - secure: "A2LGcokyu6RVwoQXShPobbZpKc3s9Q8H2PHU+RRtnJLdWRyn9YZ3A3/WN/jKYJNQ1WQ6wVsicGxJxcgkTGdVLRk5+B4WbjQXAWgMjrGqtKsB1Lj7IPcrYuUzhZFgnfbPsw0VgUCFZnpXZumN2UFtG7+6TWikj8z3viSCzSKgH+YujqU4gZFTbz03NdoNabpbbeZPecqh0Whv/6YVtRG8sKbX0MH4bXOASagYsniNr2MoopL5oL9GUbCo+a+LmOJrbdV7B2zNCCENZQea6t3LoJMtP711e7roMzIyNJ1/AXMrzD7vJPqQg7dd3kYn4wdWSYnCO4KfouDQMqORDqNKgRZEqB++A5N95lRo/Z+qlVtH1T//Uu80aMuXEgid7YrFD8VtV9jOF/1y029UiA+OGsy6Y1flxv82Cs0bp4jVo0YGFcxl0wEKaW3m6WwChUWxGLNFd9Z9uyz5T1ropBlB/STwcDY+P9GAhaL9UyZDtWql2a8nm4ZywBwv9Nr2Ufg7kbVrSwV/OAYl2/m73RK1MYCEl9x+xBEKVFHJSlBe+giexsUb6/ELKn37//2K7ZnQzDQZzS6nnjYtCHi1hxG55e/ByXhWgWFquhQI4O5/S6vyjhe2Op+PY0OZCjUSWVUXpdSWKYwtOlC+akUrqM93DrI/ZK75wT8Kw77k/7AEy5Q="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
